app-builder: v0.2.5

Application:
  name: Icarus
  asciibanner: scripts/icon/banner.txt
  icon: scripts/icon/Icarus.ico
  installdir: '%localappdata%\Ignis\Icarus'
  pause: 1

  programdata:
    - [ ./bin, ./bin ]
    - [ ./scripts, ./scripts ]
    - [ ./src, ./src ]
    - [ ./site-packages, ./site-packages ]
    - [ ./Icarus.exe, ./Icarus.exe ]

  startmenu:
    - Icarus.exe

dependencies:
  python 3.9:
    - pydicti
    - xlwings
    - minimalmodbus
    - ordered-set
    - locate
    - pyserial==3.4
    - crccheck
    
    # aa-py-core additional dependencies
    - psutil
    - numpy
    - path
    - pandas
    - filelock

    # aa-py-xl additional dependencies
    - openpyxl
    - parsimonious
    - pandasql
    